title: Site

icon: 🏗️

tabs:
  clients:
    label: Clients (ADMIN)
    sections:
      drafts:
        label: Clients
        type: pages
        templates:
          - clients
        status: all

  #       columns array  –  Columns config for layout: table
  # create    –  Optional array of templates that should only be allowed to add or false to completely disable page creation
  # empty    –  Sets the text for the empty state box
  # flip  bool  false  Enables/disables reverse sorting
  # headline    –  The headline for the section. This can be a simple string or a template with additional info from the parent page.
  # help    –  Sets the help text
  # image    –  Image options to control the source and look of preview
  # info    –  Optional info text setup. Info text is shown on the right (lists, cardlets) or below (cards) the title.
  # label    –  The label for the section. This can be a simple string or a template with additional info from the parent page.
  # layout  string  list  Section layout.
  # limit  int  20  Sets the number of items per page. If there are more items the pagination navigation will be shown at the bottom of the section.
  # max  int  –  Sets the maximum number of allowed entries in the section
  # min  int  –  Sets the minimum number of required entries in the section
  # page  int  –  Sets the default page for the pagination. This will overwrite default pagination.
  # parent  string  –  Sets the query to a parent to find items for the list
  # search  bool  false  Enable/disable the search in the sections
  # size  string  auto  The size option controls the size of cards. By default cards are auto-sized and the cards grid will always fill the full width. With a size you can disable auto-sizing. Available sizes: tiny, small, medium, large, huge
  # sortBy  string  –  Overwrites manual sorting and sorts by the given field and sorting direction (i.e. date desc)
  # sortable  bool  true  Enables/disables manual sorting
  # status  string    Filters pages by their status. Available status settings: draft, unlisted, listed, published, all.
  # templates    –  Filters the list by templates and sets template options when adding new pages to the section.
  # text    {{ model.title }}  Setup for the main text in the list or cards. By default this will display the title.

  data:
    label: Data (PUBLIC)
    fields:
      slogan:
        type: text
        label: Slogan
        placeholder: Créations visuelles pluridisciplinaires
        width: 1/2
      copyright:
        type: text
        label: Copyright
        placeholder: "{{ site.title }}"
        before: Copyright © 2022
        width: 1/2
      description:
        type: textarea
        label: Description
        buttons: false
        placeholder: Créations visuelles pluridisciplinaires
        help: SEO | Idéalement entre 150 et 300 chars
      email:
        type: email
        label: Mail
        width: 1/2
      tel:
        type: tel
        label: Téléphone
        width: 1/2
      adressRoad:
        type: text
        label: Rue
        size: small
        width: 2/6
        buttons: false
      adressNumber:
        type: text
        label: Numéro
        size: small
        width: 1/6
        buttons: false
      adressLocation:
        type: text
        label: NPA/Localité
        size: small
        width: 1/2
        buttons: false
      social:
        type: structure
        label: Réseaux sociaux
        width: 1/2
        columns:
          name:
            width: 3/1
          nickname:
            width: 4/1
          url:
            width: 7/1
        fields:
          name:
            type: text
            label: Réseau
            width: 1/2
          nickname:
            type: text
            label: Pseudo
            width: 1/2
          url:
            type: url
            label: URL

  assets:
    label: Assets (PUBLIC)
    fields:
      # Couleurs
      assetsColorsHeadline:
        type: headline
        label: Couleurs
        numbered: false
      assetsColors:
        type: structure
        label: Couleurs
        width: 1/2
        columns:
          name:
            width: 2/6
            before: --C-
          color:
            width: 4/6
        fields:
          name:
            type: text
            label: Nom
            before: --C-
            pattern: '[A-Za-z\-]+'
            help: Lettres et traits d'union uniquement
            required: true
          color:
            type: colors
            label: Couleur
            alpha: true
            default: "#000000"
            required: true
      # Font default
      assetsFontDefaultHeadline:
        type: headline
        label: Fonte principale
        numbered: false
      assetsFontDefault:
        type: files
        label: Fichier
        required: true
        uploads: font
        max: 3
        width: 1/2
        translate: false
      assetsFontDefaultFallback:
        type: textarea
        label: Fallback
        font: monospace
        buttons: false
        width: 1/2
        help: '`"Atacama VAR", Helvetica, monospace`'
        spellcheck: false
        translate: false
      assetsFontDefaultFeatureSettings:
        type: textarea
        label: font-feature-settings
        font: monospace
        buttons: false
        width: 1/2
        help: '`"ss02", "ss03", …`'
        spellcheck: false
        translate: false
      assetsFontDefaultVariationSettings:
        type: textarea
        label: font-variation-settings
        font: monospace
        buttons: false
        width: 1/2
        help: '`"wght" 450, "wdth" 100, …`'
        spellcheck: false
        translate: false
      # Font emphasis
      assetsFontEmphasisHeadline:
        type: headline
        label: Fonte secondaire
        numbered: false
        translate: false
      assetsFontEmphasis:
        type: files
        label: Fichier
        uploads: font
        multiple: false
        width: 1/2
        translate: false
      assetsFontEmphasisFallback:
        type: textarea
        label: Fallback
        font: monospace
        buttons: false
        width: 1/2
        help: '`"Atacama VAR", Helvetica, monospace`'
        spellcheck: false
        translate: false
      assetsFontEmphasisFeatureSettings:
        type: textarea
        label: font-feature-settings
        font: monospace
        buttons: false
        width: 1/2
        help: '`"ss02", "ss03", …`'
        spellcheck: false
        translate: false
      assetsFontEmphasisVariationSettings:
        type: textarea
        label: font-variation-settings
        font: monospace
        buttons: false
        width: 1/2
        help: '`"wght" 450, "wdth" 100, …`'
        spellcheck: false
        translate: false
  projets:
    label: Projects (PUBLIC)
    fields:
      pages: true
